services:
  db:
    image: postgres:16-alpine
    container_name: sillarnet_db
    environment:
      POSTGRES_USER: sillar
      POSTGRES_PASSWORD: sillar
      POSTGRES_DB: sillarnet
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sillar -d sillarnet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
